# Generated by Django 4.2.2 on 2023-06-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='markerName',
            new_name='name',
        ),
    ]
