# Generated by Django 4.2.2 on 2023-06-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_marker_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='weight',
            new_name='category_level',
        ),
    ]
