# Generated by Django 4.2.2 on 2023-06-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_roadintersection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoadIntersection',
        ),
        migrations.AddField(
            model_name='marker',
            name='type',
            field=models.CharField(choices=[(None, 'Select the type'), ('establishment', 'Establishment'), ('intersection', 'Intersection')], default='establishment', max_length=14),
        ),
        migrations.AlterField(
            model_name='marker',
            name='name',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
