# Generated by Django 4.2.2 on 2023-07-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_alter_marker_latitude_alter_marker_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='category_level',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='latitude',
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='longitude',
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='type',
            field=models.CharField(choices=[(None, 'Select the type'), ('establishment', 'Establishment'), ('intersection', 'Intersection'), ('start_dest', 'Start/Destination')], default='establishment', max_length=14, null=True),
        ),
    ]
